# Generated by Django 5.2.6 on 2025-10-02 19:23

import battles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_code', models.CharField(default=battles.models.generate_battle_code, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_battles', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_comparison', models.TextField()),
                ('performance_comparison', models.TextField()),
                ('readability_comparison', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_file', models.FileField(upload_to='code_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('complexity_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='battles.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeFile',
        ),
        migrations.AddField(
            model_name='battleresult',
            name='loser_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_battles', to='battles.codesubmission'),
        ),
        migrations.AddField(
            model_name='battleresult',
            name='winner_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_battles', to='battles.codesubmission'),
        ),
    ]
