# Generated by Django 5.2.6 on 2025-10-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleresult',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='battleresult',
            name='loser_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_battles', to='battles.codesubmission'),
        ),
        migrations.AlterField(
            model_name='battleresult',
            name='winner_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_battles', to='battles.codesubmission'),
        ),
    ]
