# Generated by Django 5.2.6 on 2025-12-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0004_battleresult_is_draw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleresult",
            name="complexity_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complexity_wins",
                to="battles.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="detailed_comparison",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="loser_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="performance_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_wins",
                to="battles.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="quality_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_wins",
                to="battles.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="score_difference",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="security_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_wins",
                to="battles.codesubmission",
            ),
        ),
        migrations.AddField(
            model_name="battleresult",
            name="winner_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="analysis_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="analysis_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="analysis_version",
            field=models.CharField(default="1.0", max_length=10),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="classes_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="cognitive_complexity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="cpu_usage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="cyclomatic_complexity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="documentation_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="flake8_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="functions_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="halstead_difficulty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="halstead_effort",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="halstead_volume",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="imports_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="lines_of_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="maintainability_index",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="memory_usage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="pylint_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="security_issues_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="security_issues_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="time_complexity_estimate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="vulnerability_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
