# Generated by Django 5.1.3 on 2025-12-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0005_battleresult_complexity_winner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="code_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="codesubmission",
            name="code_file",
            field=models.FileField(
                blank=True, null=True, upload_to="code_submissions/"
            ),
        ),
    ]
