# Generated by Django 5.2.7 on 2026-01-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0006_codesubmission_code_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Problem description in Markdown"),
                ),
                (
                    "input_format",
                    models.TextField(help_text="Description of input format"),
                ),
                (
                    "output_format",
                    models.TextField(help_text="Description of expected output format"),
                ),
                (
                    "constraints",
                    models.TextField(help_text="Constraints (e.g., 1 <= n <= 10^5)"),
                ),
                (
                    "example_input",
                    models.TextField(help_text="Example input to show users"),
                ),
                (
                    "example_output",
                    models.TextField(help_text="Expected output for example"),
                ),
                (
                    "example_explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of the example"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.FloatField(
                        default=2.0, help_text="Time limit per test case"
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.IntegerField(default=256, help_text="Memory limit in MB"),
                ),
                (
                    "function_signature",
                    models.CharField(
                        help_text="Function signature users must implement, e.g., 'def solution(nums, target):'",
                        max_length=200,
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, help_text="Starter code template for users"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="all_tests_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="avg_execution_time",
            field=models.FloatField(
                blank=True, help_text="Average execution time across tests", null=True
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="max_memory_used",
            field=models.FloatField(
                blank=True, help_text="Max memory used in MB", null=True
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="test_results",
            field=models.JSONField(
                blank=True, help_text="Detailed results for each test case", null=True
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="tests_passed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="tests_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="battle",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="battles.problemstatement",
            ),
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(help_text="Input to pass to the function"),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Expected output/return value"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Hidden tests are not shown to users"
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Sample tests shown in problem description",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of test case execution"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=10, help_text="Points for passing this test"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="battles.problemstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
