# Generated by Django 5.2.7 on 2026-01-06 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0007_problemstatement_codesubmission_all_tests_passed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="SVG icon class or name", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color for the category",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="problemstatement",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="battles.category"
            ),
        ),
        migrations.CreateModel(
            name="PracticeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_content", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("tests_passed", models.IntegerField(default=0)),
                ("tests_total", models.IntegerField(default=0)),
                ("all_tests_passed", models.BooleanField(default=False)),
                ("test_results", models.JSONField(blank=True, null=True)),
                ("avg_execution_time", models.FloatField(blank=True, null=True)),
                ("complexity_score", models.FloatField(blank=True, null=True)),
                ("performance_score", models.FloatField(blank=True, null=True)),
                ("total_score", models.FloatField(blank=True, null=True)),
                (
                    "time_complexity_estimate",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_submissions",
                        to="battles.problemstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battles_played", models.IntegerField(default=0)),
                ("battles_won", models.IntegerField(default=0)),
                ("battles_lost", models.IntegerField(default=0)),
                ("battles_drawn", models.IntegerField(default=0)),
                ("problems_solved", models.IntegerField(default=0)),
                ("easy_solved", models.IntegerField(default=0)),
                ("medium_solved", models.IntegerField(default=0)),
                ("hard_solved", models.IntegerField(default=0)),
                ("rating", models.IntegerField(default=1200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
