# Generated by Django 5.2.7 on 2026-04-12 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0008_category_problemstatement_categories_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(
                fields=["is_completed", "created_at"], name="bat_complete_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(
                fields=["creator", "is_completed"], name="bat_creator_complete_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(
                fields=["opponent", "is_completed"], name="bat_opponent_complete_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["battle", "all_tests_passed"], name="cs_battle_passed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codesubmission",
            index=models.Index(
                fields=["battle", "user", "all_tests_passed"],
                name="cs_battle_user_passed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginactivity",
            index=models.Index(fields=["timestamp"], name="la_timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="loginactivity",
            index=models.Index(
                fields=["user", "timestamp"], name="la_user_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicesubmission",
            index=models.Index(
                fields=["user", "problem", "submitted_at"],
                name="ps_user_prob_submitted_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practicesubmission",
            index=models.Index(
                fields=["user", "all_tests_passed"], name="ps_user_passed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemstatement",
            index=models.Index(
                fields=["is_active", "difficulty", "title"],
                name="prob_active_diff_title_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["problem", "is_hidden", "order"],
                name="tc_prob_hidden_order_idx",
            ),
        ),
    ]
